# Sheet 7

**Useful Links**

[Linear Regression Basics / Edx](https://www.youtube.com/watch?v=2wEROvCN9-0)

[Normal Equation](https://eli.thegreenplace.net/2014/derivation-of-the-normal-equation-for-linear-regression/)


In [0]:
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

### A. Given the data below

![alt text](https://i.ibb.co/ccFCx1z/image.png)

**How many parameter to find to solve a linear regression problem on the data?**

In [2]:
x1 = np.array([1,2,2,2,3,3,4,4,4,5])
x2 = np.array([5, 6, 10, 12, 17, 12, 6, 5, 7, 10])
Y = np.array([10 ,40 ,50 ,60 ,70 ,50 ,30 ,20 ,40 ,70])
X = np.empty((len(x1),3))
coefs_ = np.empty((6,3))
number_of_parameters = 3 # Theta 0 + 2 (Features)
print (number_of_parameters)

3


**Use Normal equations to find the equation of the line produced using linear
regression algorithm. Specify the dimensionality of each matrix carefully.
Assume no regularization ?**

In [3]:
for i in range(len(X)):
  X[i] = [1, x1[i] , x2[i]]
coefs_[0] = np.matmul(np.linalg.inv(np.matmul(X.T,X)),np.matmul(X.T,Y))
print("Equation for line: ",np.around(coefs_[0][0],decimals=2) ,"+", np.around(coefs_[0][1],decimals=2),"X1 +",np.around(coefs_[0][2],decimals=2),"X2")

Equation for line:  -7.99 + 4.29 X1 + 4.35 X2


**Use Scikit-learn package for finding the linear regression solution.**

In [4]:
reg = LinearRegression().fit(X, Y)
coefs_[1] = reg.coef_
print(reg.coef_)

[0.         4.28571429 4.34782609]


In [5]:
alphas = [0.1,1,10,100] 
for j,i in zip(range(2,6),alphas):
  reg = linear_model.Ridge(alpha=i).fit(X,Y)
  coefs_[j] = reg.coef_
  print(reg.coef_)

[0.         4.25531915 4.34467777]
[0.         4.         4.31654676]
[0.         2.5        4.05405405]
[0.         0.52631579 2.5210084 ]


In [6]:
pred_y = []
pred_y.clear()
print("Note: theta0 isn't addedd.")
points = np.array([[3,16],[2,4],[5,4]])
methods = ["Normal Equation","Scikit-Learn","Regu - Alpha = 0.1","Regu - Alpha = 1","Regu - Alpha = 10","Regu - Alpha = 100"]
for point in points:
  for method,coef_ in zip(methods,coefs_):
    print(method)
    print(np.around((coef_[1] * point[0] + coef_[2] * point[1]),decimals = 2))
  print("----")

Note: theta0 isn't addedd.
Normal Equation
82.42
Scikit-Learn
82.42
Regu - Alpha = 0.1
82.28
Regu - Alpha = 1
81.06
Regu - Alpha = 10
72.36
Regu - Alpha = 100
41.92
----
Normal Equation
25.96
Scikit-Learn
25.96
Regu - Alpha = 0.1
25.89
Regu - Alpha = 1
25.27
Regu - Alpha = 10
21.22
Regu - Alpha = 100
11.14
----
Normal Equation
38.82
Scikit-Learn
38.82
Regu - Alpha = 0.1
38.66
Regu - Alpha = 1
37.27
Regu - Alpha = 10
28.72
Regu - Alpha = 100
12.72
----


### B. Design a neural net to produce the majority function of three binary inputs

![alt text](https://i.imgur.com/M6xulLn.jpg)